services:
  nginx:
    build:
      context: .
      dockerfile: webui.Dockerfile
    image: marcorentap/hallucinet
    container_name: hallucinet
    networks:
      hallucinet:
        ipv4_address: 192.168.100.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  backend:
    image: marcorentap/hallucinet-backend
    build:
      context: .
      dockerfile: monitor.Dockerfile
    container_name: hallucinet-backend
    hostname: hallucinet-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      hallucinet:
        ipv4_address: 192.168.100.3

networks:
  hallucinet:
    name: hallucinet
    ipam:
      config:
        - subnet: 192.168.100.0/24
