services:
  hallucinet:
    image: marcorentap/hallucinet
    build: .
    container_name: hallucinet
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      hallucinet:
        ipv4_address: 192.168.100.2
      
networks:
  hallucinet:
    name: hallucinet
    ipam:
      config:
        - subnet: 192.168.100.0/24
