services:
  dns:
    image: coredns/coredns:1.12.0
    container_name: hallucinet-dns
    restart: always
    volumes:
      - ./data/coredns:/data
    networks:
      - hallucinet
    command:
      - "-conf"
      - "/data/Corefile"
  backend:
    depends_on:
      - dns
    image: marcorentap/hallucinet-backend
    container_name: hallucinet-backend
    build: ./backend
    restart: always
    volumes:
      - ./data/backend:/data/backend
      - ./data/coredns:/data/coredns
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hallucinet
      
networks:
  hallucinet:
    name: hallucinet
    ipam:
      config:
        - subnet: ${HALLUCINATE_SUBNET:-192.168.100.0/24}
