services:
  coredns:
    image: coredns/coredns:1.12.0
    restart: always
    volumes:
      - ./data/coredns:/data
    networks:
      - hallucinet
    command:
      - "-conf"
      - "/data/Corefile"
  backend:
    image: marcorentap/hallucinet-backend
    build: ./backend
    restart: always
    volumes:
      - ./data/backend:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hallucinet
      
networks:
  hallucinet:
    name: hallucinet
    ipam:
      config:
        - subnet: ${HALLUCINATE_SUBNET:-192.168.100.0/24}
