services:
  coredns:
    image: coredns/coredns:1.12.0
    container_name: coredns
    restart: always
    volumes:
      - ./data/coredns/:/data/
    networks:
      - hallucinet
    command:
      - "-conf"
      - "/data/Corefile"

networks:
  hallucinet:
    name: hallucinet
    ipam:
      config:
        - subnet: 192.168.100.0/24
